# Generated by Django 5.0.7 on 2024-07-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='admin_access',
            field=models.BooleanField(null=True),
        ),
    ]
